
swagger:
  outputDirectory: ./dist
  entryFile: 
    - ./src/controllers/*
  outputFormat: OpenApi_3
  name: Typescript-rest
  description: A Sample application using Typescipt-rest library
  license: MIT
  produces: [application/json]
  version: 0.0.1
  securityDefinitions:
    default:
      type: apiKey
      in: header
      name: Authorization
    secondAuthenticator:
      type: apiKey
      in: header
      name: Authorization